name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build the package
        run: |
          # Extract version number from github.ref and write to version.txt
          version=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "__version__=\"$version\"" > func_adl/version.txt
          hatch build
      - name: Publish a func_adl to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password_func_adl }}
